"""E2E: Upload a plugin-rendered document and verify GenericDataFields.

Uploads test_invoice.pdf (generated by scripts/generate-test-invoice.py),
waits for processing, and verifies that the GenericDataFields component
renders vendor, amount, and line item fields without console errors.

If the test_invoice.pdf fixture does not exist the test is skipped with
a message pointing to the generation script.
"""

import pytest
from pathlib import Path

from .pages.upload_page import UploadPage
from .pages.documents_page import DocumentsPage
from .pages.document_detail_page import DocumentDetailPage

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"
TEST_INVOICE = FIXTURES_DIR / "test_invoice.pdf"

SAMPLE_LOAN = (
    Path(__file__).resolve().parent.parent / "sample-documents" / "sample-loan.pdf"
)


@pytest.mark.e2e
class TestPluginRendering:
    """Verify GenericDataFields renders plugin-extracted data correctly."""

    def _upload_and_open(self, page, pdf_path, screenshot_dir, label):
        """Helper: upload a PDF, wait for processing, open detail page."""
        upload = UploadPage(page)
        upload.navigate()

        upload.upload_file(pdf_path)
        upload.submit()

        docs = DocumentsPage(page)
        docs.navigate()
        page.wait_for_timeout(3000)
        page.reload()
        page.wait_for_load_state("networkidle")

        assert docs.has_documents(), f"No documents after uploading {label}"
        docs.click_first_document()

        detail = DocumentDetailPage(page)
        detail.wait_for_processing(timeout=300_000)
        return detail

    def test_generic_data_fields_render(
        self, authenticated_page, screenshot_dir
    ):
        """Upload a document and verify extracted fields render."""
        page = authenticated_page

        # Prefer test_invoice.pdf; fall back to sample-loan.pdf
        if TEST_INVOICE.exists():
            pdf_path = TEST_INVOICE
            label = "test_invoice"
        elif SAMPLE_LOAN.exists():
            pdf_path = SAMPLE_LOAN
            label = "sample_loan"
        else:
            pytest.skip(
                "No test PDF available. Generate with: "
                "uv run python scripts/generate-test-invoice.py"
            )

        detail = self._upload_and_open(page, pdf_path, screenshot_dir, label)

        # Switch to the Extracted tab
        detail.click_tab("Extracted")
        page.wait_for_timeout(1000)

        extracted_text = detail.get_extracted_data_text()
        page.screenshot(
            path=str(screenshot_dir / f"plugin_render_{label}.png")
        )

        # Verify meaningful content was rendered (not empty / error state)
        assert len(extracted_text) > 10, (
            f"GenericDataFields appears empty: '{extracted_text[:100]}'"
        )

        # Verify no React error boundaries triggered (error overlay)
        error_overlay = page.locator("text=Something went wrong")
        assert error_overlay.count() == 0, (
            "React error boundary triggered during rendering"
        )

        # Check for console errors (JS exceptions)
        # Playwright captures console messages via page events; here we
        # just verify the page is not in an error state visually.
        error_banner = page.locator('[class*="bg-red"]')
        has_error = error_banner.count() > 0 and error_banner.first.is_visible()
        assert not has_error, "Red error banner visible on document detail page"
